title: Lucas
baseurl: /lucas
markdown: kramdown
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
disqus_shortname: lucaslionline



timeline:
- {time: "Aug 2016", place: "Beijing", content: "Started Working at Solar Decathlon China", subcontent: "Competition Manager", logo: "sdc"}
- {time: "Aug 2015", place: "West Lafayette", content: "Graduated from Purdue University"}
- {time: "Aug 2013", place: "West Lafayette", content: "Started School at Purdue University", subcontent: "Grad School, Architectural Engineering", logo: "purdue"}
- {time: "Jul 2012", place: "Shanghai", content: "Graduated from Tongji University"}
- {time: "Sep 2008", place: "Shanghai", content: "Started School at Tongji University", subcontent: "College, Building Environment and Facilities Engineering", logo: "tongji"}
- {time: "11 Mar 1990", place: "Shiping", content: "Born"}



apps:
- {name: "Gmail", icon: "gmail", href: ""}
- {name: "Outlook", icon: "outlook", href: ""}
- {name: "Alimail", icon: "alimail", href: ""}